### ISSUE TITLE
Cant create pull requests

### ISSUE THREAD

**Issue by barbarossa426** [rodion-m/ChatGPT_API_dotnet#10]
I have added a guard to the samples.Blazor project to check for a valid model and API key configuration. Unfortunately, I'm unable to create a pull request for this repo?

**Comment by rodion-m** [comment]
It's wired, because PRs are enabled. What error message is it shown? You should fork the repo before doing the PR (I guess you know it).

**Comment by rodion-m** [comment]
Close this for now, feel free to reopen it.
