### ISSUE TITLE
When the package will support chatGPT 4o-mini?

### ISSUE THREAD

**Issue by walter-234** [rodion-m/ChatGPT_API_dotnet#11]
GPT-4o mini surpasses GPT-3.5 Turbo and other small models on academic benchmarks across both textual intelligence and multimodal reasoning, and supports the same range of languages as GPT-4o. Therefore, I believe the package should support it

**Comment by rodion-m** [comment]
Thanks for using this library.
gpt-4o and gpt-4o-mini support has been added in version 4.1.0. See: https://github.com/rodion-m/ChatGPT_API_dotnet?tab=readme-ov-file#20248

**Comment by walter-234** [comment]
Thank @rodion-m
