### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by techjb** [rodion-m/ChatGPT_API_dotnet#2]
Hi. I love your library. It is easy to use and ligthweight. Could you please update de Nuget package? I need to set the MaxTokens value, but it is a protected variable in 1.1.0 version.
Thanks.

**Comment by rodion-m** [comment]
Hi @techjb ! Sorry, I missed this issue. I'll update nuget package in few days.

**Comment by rodion-m** [comment]
It'll be huge update

**Comment by rodion-m** [comment]
It's done. The updated package and docs are ready.
