### ISSUE TITLE
How do I use in a razor page? Always seems to be blocking

### ISSUE THREAD

**Issue by jay23606** [rodion-m/ChatGPT_API_dotnet#3]
![image](https://user-images.githubusercontent.com/4602056/229273772-7c02411d-5dc2-4f6b-87d5-503184f64e61.png)

**Comment by jay23606** [comment]
I got it working like this in case anyone is curious: 
![image](https://user-images.githubusercontent.com/4602056/229288119-657133ea-8a10-49f6-84da-5633d07f1262.png)

(sb is a StringBuilder and I just do &#64;sb.ToString() on markup)

**Comment by jay23606** [comment]
Added a fix with one of the methods so token size hopefully doesn't overflow:
![image](https://user-images.githubusercontent.com/4602056/229309031-a122209e-7907-47af-b204-ed4d9df9cf7a.png)

**Comment by rodion-m** [comment]
@jay23606 thanks for contributing! Feel free to ask your questions after I update the library.

**Comment by jay23606** [comment]
> @jay23606 thanks for contributing! Feel free to ask your questions after I update the library.

No problem. I still don't think I was able to get streaming working like it works with JavaScript. Not sure how to get a response.body.getReader or a TextDecoder without js interop.
